### ISSUE TITLE
Final Fantasy X-2, Items editor is bug?

### ISSUE THREAD

**Issue by Teentitanbg** [topher-au/Farplane#1]
http://imgur.com/a/k5jkC
![safasf123](https://cloud.githubusercontent.com/assets/18299575/15700097/c69eb77a-2786-11e6-84c4-6d53dc554856.png)
![asfaf12](https://cloud.githubusercontent.com/assets/18299575/15700098/c6a07a6a-2786-11e6-8aaa-d7a1a324e30a.png)
![2afasf](https://cloud.githubusercontent.com/assets/18299575/15700099/c6a0fa44-2786-11e6-982d-0c73a4fd62ef.png)

**Comment by topher-au** [comment]
Hello,

Try out 0.3.0 and let me know if the issue persists.

Thanks!

**Comment by Teentitanbg** [comment]
I used 3.0.1 .
Everything work.
--
I found Accessories's slots is bug.
They are 99 but it still stay on then I closed game and Farplane tool too then re-open, still same.
video here https://youtu.be/qu9SiBQv4tg

**Comment by topher-au** [comment]
Thanks, it's been fixed now. It was loading the item data instead of the accessory data and just giving it accessory names instead.
