### ISSUE TITLE
My cheat engine table. Hope it can help your work to improve Farplane feature ^_^

### ISSUE THREAD

**Issue by aya888888** [topher-au/Farplane#2]
Hello Topher. I've collected some table on Cheat Engine forum and merge them to one table (I dont remember all author name because there are many of them). Hope this table it can help your work

https://www.mediafire.com/?bpcczwtxp73p7vc

PS: Can you add an Apply button to Farplane. Now people can edit value of game in real time but sometime they made a mistake when edit and can't return back to the last value. I think it's better if Farplane have Apply button. People should click Apply button after edit value to make a change

**Comment by topher-au** [comment]
Thanks for your table! No doubt it will come in handy :-)

In both of the editors, you need to hit Enter to apply the change for the selected option. If you make a mistake, simply hitting the Refresh button at the top of the window will restore the current values. Hope this helps!
